image:
  - Visual Studio 2015
cache:
  - node_modules
environment:
  CSC_KEY_PASSWORD:
    secure: Cqeajvouxb90cluiDv/iJuLkFHwNERXSxjoXg7FzZZ4=
  passphrase:
    secure: ppGahvnNpvjY6+zSIe6QJdMM2OArsgn1qb2RQX4SXMmEamtJM9/fY03rTBxBVFgoRNJftJMD9I6RYLFBzdtwQw==
  matrix:
    - nodejs_version: 10
install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1')) # install appveyor decrypt tool
  - cmd: appveyor-tools\secure-file -decrypt certs/cert.pfx.enc -secret %passphrase% # decrypt certificate
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
matrix:
  fast_finish: true
version: '{build}'
shallow_clone: true
clone_depth: 1
build_script:
  - npm run make
artifacts:
  - path: dist/Ganache-$(tag).appx
  - path: dist/ganache-setup-$(tag).exe
  - path: dist/ganache-setup-$(tag).exe.blockmap
  - path: dist/latest.yml
deploy:
  release: $(tag)
  description: $(tag) - Release Title Here
  provider: GitHub
  auth_token:
    secure: w01ayU0xx5aYR68/rJbAtdtfs+6bXFhYhZkRf4aeY8ca2qikM0UWiC7G5xXeUkz9
    draft: true
    prerelease: true
    on:
      branch: master
      appveyor_repo_tag: true
